controller_joint_names: ['','SL_sensor_joint' ,'MP2_Joint', 'MP3_joint', 'W3_joint', 'W6_joint', 'MP4_joint', 'EWH2_joint', 'EW2_joint', 'W2_joint', 'W5_joint', 'W1_joint', 'W4_joint', 'EWH1_joint', 'EW1_joint',]
